### PR TITLE
Fix `nativeTab.chromeBrowser.contentWindow.messageBrowser is undefined` in startup

### PR DESCRIPTION
**Pull request by Vigilans**

### CODE REVIEW

**Comment by dillenger** [comment]
What error does this fix?

**Comment by dillenger** [comment]
Sorry, it's in the title, but I've never seen the error, how do I reproduce it?

**Comment by Vigilans** [comment]
Start the thunderbird, the welcome page will display on the message pane. Then open developer tool, the error can be seen in the console:

image

This maybe due to `messageBrowser` does not exist on the welcome page. This error has not impact on the usage, the fix is just to silence this error logging.

**Comment by dillenger** [comment]
Ah, I see it with all other extensions disabled, some other extension(s) 
must silence it too.

**Comment by dillenger** [comment]
Done, thanks.

**Pull request merged**
